{% set name = "symstore" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b54f9e050cca9dfe7200e08b8d5e4441695540f91cdca39fa047e35460f79d85

build:
  noarch: python
  number: 0
  entry_points:
    - symstore=symstore.command_line:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - symstore
  commands:
    - symstore --help

about:
  home: https://github.com/elmirjagudin/symstore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: publish PDB and PE files to symbols store
  doc_url: https://github.com/elmirjagudin/symstore/blob/v{{ version }}/README.rst
  dev_url: https://github.com/elmirjagudin/symstore/

extra:
  recipe-maintainers:
    - elmirjagudin
