{% set name = "symstore" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfcda73775c59f9ede63422b8c0a0b36b512b1b8c6e30f29de22e55888db872a

build:
  noarch: python
  number: 0
  entry_points:
    - symstore=symstore.command_line:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit
  run:
    - python >=3.6

test:
  imports:
    - symstore
  commands:
    - symstore --help

about:
  home: https://github.com/symstore/symstore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: publish PDB and PE files to symbols store
  doc_url: https://github.com/symstore/symstore/blob/v{{ version }}/README.md
  dev_url: https://github.com/symstore/symstore/

extra:
  recipe-maintainers:
    - elmirjagudin
    - elmjag
