{% set name = "symstore" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff59bdcae166a3507102d9d6b3872f5e5c48291c59e7c335f460ae88f4d409f7

build:
  noarch: python
  number: 0
  entry_points:
    - symstore=symstore.command_line:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - symstore
  commands:
    - symstore --help

about:
  home: https://github.com/symstore/symstore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: publish PDB and PE files to symbols store
  doc_url: https://github.com/symstore/symstore/blob/v{{ version }}/README.md
  dev_url: https://github.com/symstore/symstore/

extra:
  recipe-maintainers:
    - elmirjagudin
    - elmjag
