travis:
  secure:
    BINSTAR_TOKEN: FoXIHw6jHLgbvKrg2yw4HTVf+4uoDGXtHctKq92Pe1clH2MipDfDuERxbkLI3yTyhd4bBiKrEm/+7vJT99JgIzYFYtPPA9XARIKM51McEwbbWUklDbKVQE7YXQbqYwmrRXHDTF6Pm4AVYt/hIMvMg27YxRGEjR+PxKdibai/OBI1eBsA8zg1bgkH5Amm/rX2zveolxjiEPL+UNOMjmPlFnQNqdpP15MH8WF9EH+oKkHsOMcxpSsAalwIB/z0mD5Cg+kSL7x89/dcDTzFPI3cRQ3x562I8/XN21CoVcx7WIpXiOKqI83CtGXtoWL0zkeka9pvmEf/vkNgpp+d8B/0TRBGoQGOni9pMYRndUAYK8rhU7DXiyWmxTHOO3es00oMrXNLvEDqMmmeN1mbgtMQAA9Ly7oFuYwvoPdoVZngiJcrb5k96s3ZcaYPRZ+hxpbb+2oJRajUjM2B816yq434gJrT0aprhNMyTsKIvAjNV5yhTHd8CHifUX2MFvVbZkwmOv+XMP9yFIw3TngBOv5a2xTO+bG+sNfJCK9sJAJFgAjQ/mG7tcAg3W8IO2FXLHhCUv1UbAk3VObLu2C4aPe/HNr4w44iv9OxpM3RHNGcPOJ5K/nvndOf5gq2/fPM8k9E3cC9D9NAIVUatB8JpkC4Bxh+EG0ooiSG4TEWYI5tBdM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
